### ISSUE TITLE
cant run mmake and "no buildable Go source files in"

### ISSUE THREAD

**Issue by alex-leonhardt** [KyleBanks/goggles#19]
Hi,

I did the following : 

```
⇒  go get -u github.com/KyleBanks/goggles
package github.com/KyleBanks/goggles: no buildable Go source files in ~/go/src/github.com/KyleBanks/goggles
```

installed all the dependencies as per the docs on here ... then went to ```~/go/src/github.com/KyleBanks/goggles``` and then ran 

```
⇒  mmake
Makefile:54: github.com/KyleBanks/make/go/sanity: No such file or directory
make: *** No rule to make target `github.com/KyleBanks/make/go/sanity'.  Stop.
```

cheers
alex

**Comment by carbin-gun** [comment]
I was into the same problem

**Comment by KyleBanks** [comment]
Hey @alex-leonhardt, @carbin-gun thanks for checking it out and sorry for the troubles. 

I've updated the README, but `go get` actually needs to be `go get github.com/KyleBanks/goggles/...` (note the ... at the end). Also I've removed the need to use `mmake`, simply using good old fashion `make` will suffice now.

**Comment by carbin-gun** [comment]
@KyleBanks the make command execution is ok.
But it reports no buildable Go source files.

```bash
$ make
[22:33:35] Using gulpfile ~/GoProjects/src/github.com/KyleBanks/goggles/_static/gulpfile.js
[22:33:35] Starting 'beautify'...
[22:33:35] Starting 'css'...
[22:33:35] Starting 'lint'...
[22:33:35] Finished 'css' after 163 ms
[22:33:35] Finished 'lint' after 166 ms
[22:33:35] Finished 'beautify' after 182 ms
[22:33:35] Starting 'default'...
[22:33:35] Finished 'default' after 29 μs
cmd/goggles/goggles_darwin.go:9:2: no buildable Go source files in /Users/fanfu/GoProjects/src/github.com/alexflint/gallium
make: *** [build] Error 1
```

**Comment by KyleBanks** [comment]
Odd... What does `ls -l $GOPATH/src/github.com/alexflint/gallium` output?

**Comment by carbin-gun** [comment]
I got it , maybe my gallium was not complete before, I `go get` it again , the `make` is ok for now.

**Comment by alex-leonhardt** [comment]
thanks! 👍
