### ISSUE TITLE
Love the gopher loader, great idea

### ISSUE THREAD

**Issue by l3pp4rd** [KyleBanks/goggles#21]
though, how is it different from **godoc** ? godoc can host your $GOPATH locally.

**Comment by KyleBanks** [comment]
It's still early, but the idea is to provide some additional functionality unrelated to docs, for instance running tests, updating to latest version, ability to open issues (at least for GitHub repos), etc.

**Comment by l3pp4rd** [comment]
Ah, got it, probably it should mention this in readme to avoid confusion, cheers
