### ISSUE TITLE
Empty web view (?)

### ISSUE THREAD

**Issue by leonklingele** [KyleBanks/goggles#22]
What I did:

```sh
$ # clone this repo and cd into it
$ git rev-parse HEAD
a5b8070a9a91e49496c33217192dfb445e3aaa9b
$ npm install gulp
$ go get -u github.com/alexflint/gallium
$ go install github.com/alexflint/gallium/cmd/gallium-bundle
$ make
```

This opens an "empty" web view which looks like a directory listing:
![goggles](https://cloud.githubusercontent.com/assets/5585491/24208009/c7a44606-0f22-11e7-8422-f8dae6a133b0.png)

**Comment by KyleBanks** [comment]
Yikes, that's not right. Could I bug you for the following:

- MacOS version
- Go version
- contents of `~/Library/Logs/goggles.log`

**Comment by leonklingele** [comment]
This patch fixes the issue for me:

```patch
diff --git a/server/server.go b/server/server.go
index d682d8a..bd6cdf9 100644
--- a/server/server.go
+++ b/server/server.go
@@ -18,7 +18,7 @@ import (
 //    /static/...
 func New(p api.Provider, root string) *http.ServeMux {
        mux := http.NewServeMux()
-       dir := http.Dir(filepath.Join(root, "static"))
+       dir := http.Dir(filepath.Join(root, "static/_static"))
        fs := http.FileServer(dir)
        mux.Handle("/", http.StripPrefix("/static/", fs))
        api.Bind(p, mux)
```

**Comment by leonklingele** [comment]
```sh
$ go version
go version go1.8 darwin/amd64
$ sw_vers -productVersion
10.11.6
```

**Comment by KyleBanks** [comment]
Great thanks, I think I see what the issue is - make is copying the static folders incorrectly for you, I'll see if I can figure out why. Seems like your .App contains:

static/_static

Instead of just:

static/

**Comment by KyleBanks** [comment]
@leonklingele this should be resolved now but unfortunately I was never able to reproduce to be certain. If you could verify it would be much appreciated!

**Comment by leonklingele** [comment]
Works fine, thank you! :)
