### ISSUE TITLE
Fonts look blurry on retina

### ISSUE THREAD

**Issue by bits01** [KyleBanks/goggles#24]
Any tips or fixes to make them look better?

**Comment by leonklingele** [comment]
Probably a bug of [Gallium](https://github.com/alexflint/gallium).

**Comment by KyleBanks** [comment]
I think @leonklingele is correct, even in the developer tools (`cmd+d`) the fonts are all blurry. I'll see if there's anything that can be done with CSS antialiasing properties but I'm not overly optimistic.

**Comment by KyleBanks** [comment]
@bits01 @leonklingele After some digging I found the issue and I've submitted a PR to Gallium to resolve it going forward.

In the meantime, the [v0.2.0](https://github.com/KyleBanks/goggles/releases/tag/v0.2.0) release contains the fix. If you're building from source, you'll need to manually add the following lines to `Goggles.app/Contents/Info.plist` until the Gallium PR is merged:

```
<key>NSHighResolutionCapable</key>
<string>True</string>
```

**Comment by bits01** [comment]
Thank you! Looks much better now.
