### ISSUE TITLE
Goggles in the Browser

### ISSUE THREAD

**Issue by abourget** [KyleBanks/goggles#27]
Not having Windows and Linux support is a deal-breaker for me. I often see apps that only publish the binary that includes the assets in it (like https://github.com/sosedoff/pgweb ).. this allows it to run remotely (with a port-forward), locally and using your current browser.. 

Are we using any features of Gallium that make it interesting ? Otherwise, could we simply publish the binary + assets (with https://github.com/GeertJohan/go.rice or something) ?

thanks for goggles :) !

**Comment by KyleBanks** [comment]
Yeah I agree. Originally I had thought the native capabilities might end up being useful, but many people have mentioned how bummed they are that it's Mac only, so it's not worth it. 

Right now I'm thinking to go down the route of:

1. On Mac you could run as a standalone .app or in the browser.
2. Linux/Windows/etc you can run in the browser.

It should be pretty easy to do this, but I won't have much time until next week unfortunately. If you're interested in taking this on I can definitely point you in the right direction! There's very little actual native functionality so not much has to change to make this work.

**Comment by KyleBanks** [comment]
Alright, managed to squeeze this in! 

It's available in [v0.3.0](https://github.com/KyleBanks/goggles/releases/tag/v0.3.0), and I could definitely use some help testing this one out.

**Comment by abourget** [comment]
Hey thanks a whole lot :)

There's still the `Terminal` button that does nothing under Linux. The rest works pretty well in Chrome :) and it opens automatically :) links to the repos nicely, etc..

**Comment by KyleBanks** [comment]
Awesome glad to hear it! Which OS did you try it on?

And yeah I opened #28 for the Terminal issue, it was an oversight on my part when I considered it "done". Will work on that soon.

**Comment by KyleBanks** [comment]
Oh nvm, linux... I'm tired haha.
