### ISSUE TITLE
Standalone on MacOS repeatedly asks to allow incoming connections

### ISSUE THREAD

**Issue by integrii** [KyleBanks/goggles#30]
This is likely because the app is not signed properly.  I have no idea how that process really works, though.

**Comment by KyleBanks** [comment]
Yeah Mac/iOS signing is a pain, I was hoping to avoid it but it seems I'll need to get this setup. Any chance you have a screenshot or logs of the prompt?

**Comment by KyleBanks** [comment]
@integrii seems you can get around this by following the instructions here for the time being: https://support.apple.com/en-us/HT201642

Will open another ticket for properly signed .app releases
