### ISSUE TITLE
Newcomer's first install failed

### ISSUE THREAD

**Issue by kisPocok** [KyleBanks/goggles#36]
Hi Gogglers,

I tried to install the app on Mac OS but it fails. My terminal says:
```
$ go get github.com/KyleBanks/goggles/cmd/goggles
# github.com/KyleBanks/goggles/server/api
src/github.com/KyleBanks/goggles/server/api/pkg.go:17: undefined: sort.Slice
```

Could you help me?

**Comment by KyleBanks** [comment]
Hey! sort.Slice is a new feature in Go 1.8 so you'll need to upgrade in order to build from source.

**Comment by KyleBanks** [comment]
Just updated the docs to mention the 1.8 requirement

**Comment by KyleBanks** [comment]
@kisPocok btw you can grab the latest version of Go [here](https://golang.org/dl/)
